# Numpy Mini Project

**TO Do:**

Import the numpy package under the name `np`

In [56]:
import numpy as np

Create a null vector of size 10 but the fifth value which is 1

In [57]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Create a 3x3 matrix with values ranging from 0 to 8

In [58]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

How to compute ((A+B)*(-A/2)) in place (without copy)?

In [59]:
A = np.random.randint(low = 0, high = 10,size = 100)
B = np.random.randint(low = 0, high = 10,size = 100)
C = ((A+B)*(-A/2))
print(C)
# np.add(A, B, out=B)
# np.divide(A, 2, out=A)
# np.negative(A, out=A)
# np.multiply(A, B, out=A)

[-56.  -17.5 -14.  -42.  -32.    0.  -14.  -15.  -67.5  -2.  -36.  -42.
 -21.  -24.   -7.5 -56.   -7.  -31.5 -38.5 -58.5  -3.5   0.    0.    0.
 -24.5 -21.   -5.  -15.  -64.  -12.  -26.   -2.    0.   -4.   -9.  -15.
 -24.  -15.   -5.    0.   -6.  -31.5 -42.   -4.   -2.  -12.5   0.  -52.5
 -27.  -52.  -31.5  -5.  -81.  -17.5   0.  -11.   -6.  -39.  -20.  -60.
 -38.5 -18.    0.  -45.  -45.5 -64.   -4.  -52.   -4.  -42.  -68.  -30.
   0.  -22.5 -15.  -20.   -4.5 -40.  -44.  -18.  -63.  -20.  -72.  -11.
  -9.  -49.   -2.    0.  -72.  -30.   -2.5  -4.   -3.   -3.  -15.   -5.
  -5.   -4.5  -9.   -7.5]

Create a 5x5 matrix with row values ranging from 0 to 4

In [60]:
x = np.zeros((5, 5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]

Consider two random array A and B, check if they are equal

In [61]:
A = np.arange(10)
B = np.arange(10)
np.array_equal(A, B)

True

Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [62]:
Z = np.random.random((100, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X ** 2 + Y ** 2)
#T = np.arctan2(Y, X) #polar coordinates
print(R)
#print(T)

[1.08289606 0.39571225 0.24925419 0.92380788 0.3632733  0.87474792
 0.58130287 1.13041195 0.59516234 0.91041634 0.99739451 1.15793624
 0.9999472  0.99253136 0.93182367 0.2090221  0.83934426 0.62469631
 0.93889252 0.2753172  0.76210668 1.27656343 1.0903605  0.93699602
 1.10029199 0.46494299 0.83553873 0.92293117 0.81268081 1.14676486
 0.70050815 0.34924643 0.79159868 0.74253386 0.87697027 0.66563187
 0.84871571 0.3060005  0.98147414 0.42938163 1.2175262  0.80994689
 1.06022749 0.74789502 0.69404637 1.26329931 0.3405112  0.43170945
 0.52970713 0.42931873 0.83840809 1.3378501  1.13695526 0.18199039
 0.58011835 0.71399903 1.15201042 0.32383844 1.03068065 1.09635735
 1.08741209 0.67019476 0.96225496 0.80994102 0.49878867 0.72602697
 0.76311921 0.33456031 0.73389723 1.05668098 0.66529373 0.99246381
 0.83940504 0.93969874 0.91351475 0.87148016 0.28147761 0.90706936
 0.40477338 0.44960829 0.96508876 1.1002198  0.76424527 0.93308553
 0.51332945 0.80232636 0.95605687 0.82854153 0.41232155 1.04878469
 0.44075819 1.01565249 0.5190488  0.44815608 0.30170281 0.41928137
 1.16689657 1.05401134 0.47312657 0.34306812]

Subtract the mean of each row of a matrix

In [63]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True) #b = a - a.mean(axis=1, keepdims=True)
print(Y)

[[ 0.34033608 -0.07194832  0.26955555  0.27787628 -0.21759188 -0.26539989
  -0.0367857   0.15151279 -0.40234087 -0.04521405]
 [-0.12100577  0.09747957  0.20260318 -0.13247151  0.19084495  0.11735523
  -0.25273806  0.27399504  0.1601616  -0.53622423]
 [-0.31205346  0.21010892 -0.39057781  0.39055315  0.36898415 -0.08506889
   0.30109664  0.02160449 -0.14324649 -0.3614007 ]
 [-0.23359638  0.64136948 -0.31507914  0.27171216  0.48837984 -0.19997763
   0.07646338 -0.18782285 -0.32138037 -0.22006851]
 [ 0.46211332 -0.35141471 -0.29810768 -0.29336565  0.12576581 -0.13092632
   0.21844335  0.50865523  0.06941662 -0.31057997]]

How to sort an array by the nth column?

In [64]:
nums = np.random.randint(0,10,(3,3))
print(nums)
print(nums[nums[:,1].argsort()]) #a = a[a[:,n-1].argsort()]

[[2 5 3]
 [8 6 9]
 [3 8 8]]
[[2 5 3]
 [8 6 9]
 [3 8 8]]

How to tell if a given 2D array has null columns?

In [65]:
nums = np.random.randint(0,3,(4,10))
print(nums)
print((~nums.any(axis=0)).any())

[[1 0 2 0 0 0 0 1 2 2]
 [2 0 0 2 0 2 1 0 2 1]
 [2 0 1 2 2 1 2 1 2 1]
 [2 1 0 1 0 1 1 0 2 1]]
False

Considering a four dimensions array, how to get sum over the last two axis at once?

In [66]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[60 45 52 40]
 [58 70 36 56]
 [52 50 55 60]]

Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [67]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]

Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles

In [68]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 62) ( 2, 92) ( 3, 30) ( 3, 35) ( 4, 29) ( 4, 65) ( 6, 53) ( 6, 73)
 (23, 34) (23, 88) (29, 65) (30, 35) (30, 57) (30, 66) (30, 76) (30, 83)
 (31, 39) (31, 94) (34, 88) (39, 62) (39, 66) (39, 94) (43, 63) (43, 95)
 (53, 73) (57, 76) (62, 66) (62, 92) (63, 95) (66, 83)]

Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [69]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 1 2 3 4 5 6 7]

How to get the n largest values of an array

In [70]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]

**Mini-project NumPy:**

Mean Normalization


In machine learning we use large amounts of data to train our models. Some machine learning algorithms may require that the data is normalized in order to work correctly. The idea of normalization, also known as feature scaling, is to ensure that all the data is on a similar scale, i.e. that all the data takes on a similar range of values. For example, we might have a dataset that has values between 0 and 5,000. By normalizing the data we can make the range of values be between 0 and 1.

In this lab, you will be performing a different kind of feature scaling known as mean normalization. Mean normalization will scale the data, but instead of making the values be between 0 and 1, it will distribute the values evenly in some small interval around zero. For example, if we have a dataset that has values between 0 and 5,000, after mean normalization the range of values will be distributed in some small range around 0, for example between -3 to 3. Because the range of values are distributed evenly around zero, this guarantees that the average (mean) of all elements will be zero. Therefore, when you perform mean normalization your data will not only be scaled but it will also have an average of zero.

To Do:


You will start by importing NumPy and creating a rank 2 ndarray of random integers between 0 and 5,000 (inclusive) with 1000 rows and 20 columns. This array will simulate a dataset with a wide range of values. Fill in the code below

In [71]:
# import NumPy into Python
import numpy as np

# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0, 5001, (1000,20))

# print the shape of X
X.shape

(1000, 20)

Now that you created the array we will mean normalize it. We will perform mean normalization using the following equation:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. In other words, mean normalization is performed by subtracting from each column of $X$ the average of its values, and then by dividing by the standard deviation of its values. In the space below, you will first calculate the average and standard deviation of each column of $X$.

In [72]:
# Average of the values in each column of X
ave_cols = np.mean(X, axis=0)

# Standard Deviation of the values in each column of X
std_cols = X.std(axis=0)

If you have done the above calculations correctly, then `ave_cols` and `std_cols`, should both be vectors with shape `(20,)` since $X$ has 20 columns. You can verify this by filling the code below:

In [73]:
# Print the shape of ave_cols
print(ave_cols.shape)
# Print the shape of std_cols
print(std_cols.shape)

(20,)
(20,)

You can now take advantage of Broadcasting to calculate the mean normalized version of $X$ in just one line of code using the equation above. Fill in the code below

In [74]:
# Mean normalize X
X_norm = (X - ave_cols)/std_cols

If you have performed the mean normalization correctly, then the average of all the elements in $X_{\tiny{\mbox{norm}}}$ should be close to zero, and they should be evenly distributed in some small interval around zero. You can verify this by filing the code below:

In [75]:
# Print the average of all the values of X_norm
print(np.mean(X_norm, axis=0))
# Print the minimum value of each column of X_norm
print(np.min(X_norm, axis=0))
# Print the maximum value of each column of X_norm
print(np.max(X_norm, axis=0 ))

[-1.67199588e-16 -5.73985304e-17  9.02888875e-17  1.42996726e-16
 -7.02216063e-17 -9.15933995e-18  1.00253139e-16  1.53654867e-16
 -1.69864123e-16  1.48769885e-16  7.04991621e-18 -1.40998324e-16
 -1.01252340e-16  2.29816166e-17 -8.07132139e-17 -7.13873405e-17
  1.14463994e-16  7.94919686e-17 -4.21884749e-18  1.67199588e-16]
[-1.72351872 -1.7153302  -1.79652989 -1.74971241 -1.67915996 -1.75636438
 -1.71944688 -1.78071632 -1.74992951 -1.67957377 -1.72131221 -1.78892827
 -1.79091732 -1.73481477 -1.70551681 -1.75127764 -1.77116496 -1.70066935
 -1.77285487 -1.75024859]
[1.71243372 1.73465816 1.6644061  1.76549486 1.65610213 1.69348421
 1.68566727 1.68756947 1.69793497 1.66385104 1.7358673  1.78070682
 1.70465948 1.70758649 1.78602385 1.73030305 1.72568835 1.8332726
 1.72784963 1.68016463]

You should note that since $X$ was created using random integers, the above values will vary. 

# Data Separation

After the data has been mean normalized, it is customary in machine learnig to split our dataset into three sets:

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The dataset is usually divided such that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. 

In this part of the lab you will separate `X_norm` into a Training Set, Cross Validation Set, and a Test Set. Each data set will contain rows of `X_norm` chosen at random, making sure that we don't pick the same row twice. This will guarantee that all the rows of `X_norm` are chosen and randomly distributed among the three new sets.

You will start by creating a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this by using the `np.random.permutation()` function. The `np.random.permutation(N)` function creates a random permutation of integers from 0 to `N - 1`. Let's see an example:

In [76]:
# We create a random permutation of integers 0 to 4
np.random.permutation(5)

array([3, 4, 1, 2, 0])

# To Do

In the space below create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this in one line of code by extracting the number of rows of `X_norm` using the `shape` attribute and then passing it to the  `np.random.permutation()` function. Remember the `shape` attribute returns a tuple with two numbers in the form `(rows,columns)`.

In [77]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row_indices = np.random.permutation(X_norm.shape[0])
print(row_indices)

[669 454 403 865 898 166  77 242 682 141 917 555 786 714 152 455 549  33
 485 147  50 808 101 826  87 659  10 428 436 751 327  71  38 581 624 459
 413 796 845  96 715 358 392 458 981 478 214 487 772 406 626 551  95  52
 277 969 442 367 988 312 580 806 976 832 846   9 650 391 498 416 623 966
 735 690 563 994 117 739 782 328 374 303 269 381 655 533 421 885 185 836
 177 852 938 500 638 999 371 433 597 271 448 507 252 133 809 761 942 465
  88 251 530 793 161 512  80  64 663 868 492 236 762 805 712 345 256  97
 720 124 671 502 463 755 484  55 438  67 766 280 237 103 444  22 974 568
 262 875 593 630 764 243 790 998 636 457 187 482 159 584 841 123 620 923
 528 640 666 118 318 268 907 531 582 113 953 769 579 149 616 258 831 106
 598  46 116 216 265  73 753 469 248 887 771 259 679 807 554 231 466 729
 889 503 958 658 385 235 925 178 901 119 893 382  31 390 827 275   6 978
 571 708 132 547 249 935 858 218 572 905 445 984 335 204 629 933 241 352
 462 110 973 891 420 853 927 990  25 703 835   7 286 267 372 717 283 585
 396 910 975 473 965 931 285 780 510 908 685 429 706 376 441 189 959 909
 590  82 529 862 562 292 105 516 918  12 681 591 341 143 331 287  39 193
 230 964  74 838 401 494 264 894 198 954 646 226 284 282 983  61 490 474
 867 919 544 632 828 321 781 759 432 217 125 153  41 477 339 854 810 686
 527 201 833  43 977  86 388 716 637 240 273 558 987 140 483 892 165 363
 860  72 699 514 877 599 851 384 922 543 576 899 823 814 357 244  19 675
  26 497  60 566 300 600 667 698 783 926 628 232 553 651 266 989  70 437
 351 850 344 518 210 691 622 142 986 800 928  93 734 817 324   1 653 654
 333 176 967 882 752 181 313 130 864  63 676 788 820 120 947 943 532  13
  24 168 517 274 627 789 347 207 323 402 586 227 702 595 330 255 673 884
 138 670 194 408  23 435 311 680 192 223  62 641 393 839 434 645 137 949
 234 731 536 608 609  40 476 449 639 567 844 802 299 304 548 136 425 611
 186 389 349 768 470 961 272 526 633 488 770 409 422 520 903  76 795 897
 424 948 929 721 665 985 175  84 995 155 102 784 200 491 737 453 607 649
 427 348  69 203 238 228  48   8 229  56 505  14 206 415 519 213 515 776
 779 196 179 150 535 757 506 246  47 723 239 613 963 785 405 718 724 325
 588 431 375 379 916  35 245 605 798  90 199 296 754 170 758 128  49  15
 857 294 725 221 811 205  98 297 876 847 443 121 439 968 410 157 560 683
  53 317 914 940 913 602 647 346 107 114 397 705 631 399 310 859 934 674
  30 678 895 301 145 174 643 707 704 263 672 634 791 747 288 538 763 508
 742 257  32 583 957 158 364 522 276 743 745 146 524 736 368 727 167 479
 450 824 472 342 822 552 480 499 972 151  21 740 293 932 496 394 575   5
 426 493   3 219 417 773 414 557 596 803 688 856 521 941 467  83 182 733
 407  68 316  78 112 534 154 254 945 373 378 539 577 730 767 377 979 843
 404 709 982 250 883 837 215 564 748 418 799 171 888 697 618  18 540 253
  66 386   4 574 148 260 211 915 668  79  57 109 960 890 222 270   0 525
 162 794 951 900 115 309 456 111 610 696  51 879 937 320 728 804 122 471
 606 946 461 387 135 350 750  91 710 797  75 662 955 307 787 163 440 873
 694 726 921 501 261 825 930 812 139 195 447 700 191  59 570  58 970 603
 872   2 848 188 134 818 617 359 355 635  81 190 687 661 475 233 546 550
 481 398 326 830 962 329 197 366 334 208  29 305 340  16 180 689 881 819
 369 169 587 912 322 354 290 289 684 801 383 612 722 880 400  45 279 863
 695 338 621 778 834 589 746 537  20 489 760 495 601 565 212 511 936 992
  34 652 104 362 664 775 468 874 777 904 578 460 423 343 648  92 849 741
 906 711 774 765 871 224 869 920 513 411 306 744 866 361 360 792 126 337
 840 332 693 183  85 545 677 924 319 952 997  44 278 173 642 604 950 156
 295 870 144 315  54 419 225 713 209  42 561 127 657 619  37 573 308 842
 281 939 821  17 980 719 353 738 991 247 202 464 816 749 692 184 108 956
  28 172 380 395 855 430  11 815 504  94 569 452 365 291 541 996 993 542
 556 486 160 660 302 314  36 336  65 615 220 451 625 412 592 813  89 971
  27 944 509 614 356 644 902 829 878 370 911 100 756 594 896  99 523 131
 129 861 446 559 656 298 732 701 886 164]

Now you can create the three datasets using the `row_indices` ndarray to select the rows that will go into each dataset. Rememeber that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. Each set requires just one line of code to create. Fill in the code below

In [78]:
print(X_norm[row_indices[0:600]])

[[-0.57499179 -1.58601615  0.4694272  ...  1.33793965 -1.33359763
  -1.56388811]
 [ 0.68151044  0.63099381  0.01221788 ...  0.24239639 -1.45799528
   0.05606758]
 [ 1.29566286 -0.1476566  -1.40097456 ...  1.24865217 -0.20769347
  -0.8929904 ]
 ...
 [-0.09769975  1.55002258 -0.8911169  ...  0.92126472 -0.10929985
   1.51865221]
 [-0.81226232  0.63721748  1.048559   ...  1.81130505 -0.99695088
  -0.85295741]
 [-1.69807232  1.15931434 -0.90358624 ...  0.7852076   0.26319029
   0.14096514]]

In [79]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.


# Create a Training Set
X_train = X_norm[row_indices[:600]]

# Create a Cross Validation Set
X_crossVal = X_norm[row_indices[600:800]]

# Create a Test Set
X_test = X_norm[row_indices[800:]]

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
# # Make any necessary calculations.
# # You can save your calculations into variables to use later.


# # Create a Training Set
# X_train = X_norm[row_indices[:600]]

# # Create a Cross Validation Set
# X_crossVal = X_norm[row_indices[600:800]]

# # Create a Test Set
# X_test = X_norm[row_indices[800:]]

''

If you performed the above calculations correctly, then `X_tain` should have 600 rows and 20 columns, `X_crossVal` should have 200 rows and 20 columns, and `X_test` should have 200 rows and 20 columns. You can verify this by filling the code below:

In [80]:
# Print the shape of X_train
print ("shape of X_train is:",X_train.shape)

# Print the shape of X_crossVal
print ("shape of X_crossVal is:",X_crossVal.shape)

# Print the shape of X_test
print ("shape of X_test is:",X_test.shape)

shape of X_train is: (600, 20)
shape of X_crossVal is: (200, 20)
shape of X_test is: (200, 20)